name: Lint Actions and Specs

on: [push]

jobs:
  lint-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: lint-actions
      run: |
        make lint-actions

  lint-specs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: lint-specs
      run: |
        make lint-specs